In [1]:
a <- "nak"
cat(paste(a))

nak

In [2]:
data <- read.csv("synthetic_dataset.csv")

In [3]:
head(data)
View(data)

  Category Price Rating   Stock        Discount
1          5548  1.870322               0
2          3045  4.757798              38
3          4004        NA In Stock      0
4          4808  1.492085              33
5          1817        NA Out of Stock 23
6          3522        NA              NA

     Category Price Rating   Stock        Discount
1             5548  1.870322               0
2             3045  4.757798              38
3             4004        NA In Stock      0
4             4808  1.492085              33
5             1817        NA Out of Stock 23
6             3522        NA              NA
7    C         667  3.668341 In Stock     41
8    A        7125  4.983998 Out of Stock  7
9    A        2777  2.678384 In Stock      6
10             463  4.626187               3
11   A        1151  2.947838              NA
12   A        3772  4.890750 In Stock     45
13            7719  2.982242 In Stock      4
14   C        8416  1.270943              29
15   B        8530        NA              10
16   A        7936  3.032832 In Stock     44
17   B        9319  3.479064 In Stock     28
18              NA  4.097464              40
19   D        2066        NA              30
20   B        1784        NA              12
21            5589        NA              39
22   C          NA        NA Out of Stock 25
23            4176  2.264051 In Stock     42
24   D         407  2.774270 In Stock     44
25            7011        NA In Stock     38
26            8418        NA              NA
27            3405        NA In Stock     48
28   D        1732        NA              NA
29   B        5850  2.264393 Out of Stock 43
30              NA  2.357527              22
⋮    ⋮        ⋮     ⋮        ⋮            ⋮
4333          6068        NA Out of Stock 38
4334 D        2424  4.716295 In Stock     49
4335          8598        NA              27
4336          2313  4.312297 Out of Stock 42
4337          1923        NA              21
4338          7892        NA              42
4339          3796        NA Out of Stock 10
4340          6807  4.195968 In Stock      9
4341 C        6671        NA Out of Stock 27
4342          9874  3.881828               5
4343 D        9847  3.667649 Out of Stock 49
4344 B         843  2.752754 Out of Stock 48
4345            NA        NA               0
4346 B        7421        NA Out of Stock 32
4347 A        5709        NA              48
4348          3561  3.393292 In Stock     NA
4349          8954  2.532679              44
4350 A        7779        NA In Stock     29
4351          8030  4.391910 Out of Stock 20
4352 B        6525        NA Out of Stock NA
4353          8230  2.410736 Out of Stock 29
4354          5788        NA              11
4355          1556  1.433035 In Stock     NA
4356            NA        NA In Stock     46
4357            NA        NA Out of Stock 21
4358          4436  4.728335              49
4359 B        6236        NA Out of Stock  4
4360          3283        NA Out of Stock  9
4361 D        2999  4.425995              40
4362            NA  2.184471               0

In [4]:
data

     Category Price Rating   Stock        Discount
1             5548  1.870322               0
2             3045  4.757798              38
3             4004        NA In Stock      0
4             4808  1.492085              33
5             1817        NA Out of Stock 23
6             3522        NA              NA
7    C         667  3.668341 In Stock     41
8    A        7125  4.983998 Out of Stock  7
9    A        2777  2.678384 In Stock      6
10             463  4.626187               3
11   A        1151  2.947838              NA
12   A        3772  4.890750 In Stock     45
13            7719  2.982242 In Stock      4
14   C        8416  1.270943              29
15   B        8530        NA              10
16   A        7936  3.032832 In Stock     44
17   B        9319  3.479064 In Stock     28
18              NA  4.097464              40
19   D        2066        NA              30
20   B        1784        NA              12
21            5589        NA              39
22   C          NA        NA Out of Stock 25
23            4176  2.264051 In Stock     42
24   D         407  2.774270 In Stock     44
25            7011        NA In Stock     38
26            8418        NA              NA
27            3405        NA In Stock     48
28   D        1732        NA              NA
29   B        5850  2.264393 Out of Stock 43
30              NA  2.357527              22
⋮    ⋮        ⋮     ⋮        ⋮            ⋮
4333          6068        NA Out of Stock 38
4334 D        2424  4.716295 In Stock     49
4335          8598        NA              27
4336          2313  4.312297 Out of Stock 42
4337          1923        NA              21
4338          7892        NA              42
4339          3796        NA Out of Stock 10
4340          6807  4.195968 In Stock      9
4341 C        6671        NA Out of Stock 27
4342          9874  3.881828               5
4343 D        9847  3.667649 Out of Stock 49
4344 B         843  2.752754 Out of Stock 48
4345            NA        NA               0
4346 B        7421        NA Out of Stock 32
4347 A        5709        NA              48
4348          3561  3.393292 In Stock     NA
4349          8954  2.532679              44
4350 A        7779        NA In Stock     29
4351          8030  4.391910 Out of Stock 20
4352 B        6525        NA Out of Stock NA
4353          8230  2.410736 Out of Stock 29
4354          5788        NA              11
4355          1556  1.433035 In Stock     NA
4356            NA        NA In Stock     46
4357            NA        NA Out of Stock 21
4358          4436  4.728335              49
4359 B        6236        NA Out of Stock  4
4360          3283        NA Out of Stock  9
4361 D        2999  4.425995              40
4362            NA  2.184471               0

In [ ]:
data$